### ISSUE TITLE
raco setup fails

### ISSUE THREAD

**Issue by mfelleisen** [soegaard/racket-poppler#4]
I tried to install your package and got this: 

% raco pkg install racket-poppler
.....
.....
raco setup: 0 running: <pkgs>/racket-poppler/racket-poppler/main.scrbl
default-load-handler: cannot open module file
  module path: (lib "main.scrbl" "racket-poppler")
  path: /Users/matthias/plt/racket/share/pkgs/racket-poppler/racket-poppler/main.scrbl
  system error: No such file or directory; errno=2
  context...:
   standard-module-name-resolver
   /Users/matthias/plt/pkgs/racket-pkgs/racket-index/setup/scribble.rkt:895:0: load-doc/ensure-prefix
   /Users/matthias/plt/pkgs/racket-pkgs/racket-index/setup/scribble.rkt:1146:13
   /Users/matthias/plt/racket/collects/setup/parallel-do.rkt:420:20: loop

raco setup: --- installing collections ---

I am on Mac OS X 10.7+++. Let me know whether you need anything else.

**Comment by sorawee** [comment]
I got the same error that @mfelleisen was getting...

**Comment by sorawee** [comment]
I think I found the problem. The generated PDF has the following line:

```
\usepackage[active,tightpage,pdftex]{preview}
```

However, this will not generate any page (see http://tex.stackexchange.com/questions/146511/using-usepackageactive-tightpagepreview-does-not-generate-any-page). Changing the line to

```
\usepackage[active,tightpage,textmath]{preview}
```

will generate the file properly, although I'm not sure if this is what you actually want or not.

**Comment by soegaard** [comment]
Hi @sorawee and @mfelleisen 

I have committed a fix. 

Note: I tested on a newly installed version of TexLive 2015 on OS X El Capitan.
I don't know if it changes anything, but prior to finding the fix, I updated
the LaTeX classes/packages "standalone" and "preview" like this:

    sudo tlmgr update standalone
    sudo tlmgr update preview

**Comment by formalizm** [comment]
> ... contract violation expected: pdf?

The issue with empty PDFs still persists. Configuration: Windows 10, TeX Live 2022.

**Comment by soegaard** [comment]
After booting my Windows computer, I got the following working on Racket 8.4 and with TexLive 2020.
Note that any problem with the LaTeX results in an empty pdf.
To see the LaTeX log, simply insert

     (latex-debug? #t)
     
when you run into an empty pdf.

If `pdflatex` is in the Windows search path, I think Poppler picks it up automatically,
but if not you can use `latex-path` to set it manually - see below.

Finally, if you are using DrRacket: convert the picts to bitmap to see them in the repl.
[There is no problems with saving picts as svg or pdf - it's just the way the repl in 
DrRacket is implemented that makes the conversion to bitmap necesssary.]

```
#lang racket
(require latex-pict pict racket-poppler/render-tex)

(latex-debug? #t)
(latex-path 
 (case (system-type)
   [(windows) "c:/texlive/2020/bin/win32/pdflatex.exe"]))


; make a Racket pict from a piece of TeX
(define p (tex-math "\\sqrt{x^2+y^2+z}"))

(pict->bitmap p)

(define beside hc-append)
(define above  vc-append)

(pict->bitmap  ; pict->bitmap is need in DrRacket 
 ;               DrRacket won't display picts that draw directly
 ;               to the Cairo drawing context
 
 ; This shows that the pict can be used as a normal pict.
 (above (beside (rotate p (- pi (/ pi 3))) (rotate p    (/ pi 3)))
        (beside (rotate p (+ pi (/ pi 3))) (rotate p (- (/ pi 3))))))

(pict->bitmap p)

(define (tex s) (pict->bitmap (inset (tex-math s) 4)))
```

**Comment by formalizm** [comment]
This works indeed, and produces the following tex:
```
\documentclass{standalone}
\usepackage[active,tightpage,lyx,pdftex,textmath]{preview}

\begin{document}
\(\sqrt{x^2+y^2+z}\)
\end{document}
```

This: `(latex->pict "$\\sqrt{x^2+y^2}$" #:preamble #f)` (as recommended by https://github.com/formalizm/racket-poppler/blob/master/README.md), however, doesn't work, as it produces the following tex:
```
\documentclass{standalone}
\usepackage[active,tightpage,lyx,pdftex]{preview}

\begin{document}
$\sqrt{x^2+y^2}$
\end{document}
```

As I understood after some investigation, TeX package `preview` changed many years ago to skip $-math not enclosed in `\begin{preview}` ... `\end{preview}`.

P.S. Obviously at certain point `#:preamble` became by mistake a mandatory function argument.
